<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Local', 'doctrine');

/**
 * BaseLocal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_local
 * @property string $nombre_local
 * @property string $descripcion_local
 * @property integer $category_id
 * @property string $direccion
 * @property float $lat
 * @property float $lng
 * @property blob $the_geom
 * @property LocalCategory $LocalCategory
 * 
 * @method integer       getIdLocal()           Returns the current record's "id_local" value
 * @method string        getNombreLocal()       Returns the current record's "nombre_local" value
 * @method string        getDescripcionLocal()  Returns the current record's "descripcion_local" value
 * @method integer       getCategoryId()        Returns the current record's "category_id" value
 * @method string        getDireccion()         Returns the current record's "direccion" value
 * @method float         getLat()               Returns the current record's "lat" value
 * @method float         getLng()               Returns the current record's "lng" value
 * @method blob          getTheGeom()           Returns the current record's "the_geom" value
 * @method LocalCategory getLocalCategory()     Returns the current record's "LocalCategory" value
 * @method Local         setIdLocal()           Sets the current record's "id_local" value
 * @method Local         setNombreLocal()       Sets the current record's "nombre_local" value
 * @method Local         setDescripcionLocal()  Sets the current record's "descripcion_local" value
 * @method Local         setCategoryId()        Sets the current record's "category_id" value
 * @method Local         setDireccion()         Sets the current record's "direccion" value
 * @method Local         setLat()               Sets the current record's "lat" value
 * @method Local         setLng()               Sets the current record's "lng" value
 * @method Local         setTheGeom()           Sets the current record's "the_geom" value
 * @method Local         setLocalCategory()     Sets the current record's "LocalCategory" value
 * 
 * @package    geo_search
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocal extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('local');
        $this->hasColumn('id_local', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_local', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('descripcion_local', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('direccion', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('lat', 'float', 10, array(
             'type' => 'float',
             'size' => 10,
             'scale' => 6,
             'length' => 10,
             ));
        $this->hasColumn('lng', 'float', 10, array(
             'type' => 'float',
             'size' => 10,
             'scale' => 6,
             'length' => 10,
             ));
        $this->hasColumn('the_geom', 'blob', null, array(
             'type' => 'blob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LocalCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}