<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LocalCategory', 'doctrine');

/**
 * BaseLocalCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $descripcion_categoria
 * @property string $url_icono_categoria
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Local
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getDescripcionCategoria()  Returns the current record's "descripcion_categoria" value
 * @method string              getUrlIconoCategoria()     Returns the current record's "url_icono_categoria" value
 * @method timestamp           getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()             Returns the current record's "updated_at" value
 * @method Doctrine_Collection getLocal()                 Returns the current record's "Local" collection
 * @method LocalCategory       setId()                    Sets the current record's "id" value
 * @method LocalCategory       setName()                  Sets the current record's "name" value
 * @method LocalCategory       setDescripcionCategoria()  Sets the current record's "descripcion_categoria" value
 * @method LocalCategory       setUrlIconoCategoria()     Sets the current record's "url_icono_categoria" value
 * @method LocalCategory       setCreatedAt()             Sets the current record's "created_at" value
 * @method LocalCategory       setUpdatedAt()             Sets the current record's "updated_at" value
 * @method LocalCategory       setLocal()                 Sets the current record's "Local" collection
 * 
 * @package    PuntoSeguro
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocalCategory extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('local_category');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('descripcion_categoria', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('url_icono_categoria', 'string', 140, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 140,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Local', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}