<?php

/**
 * Local
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    geo_search
 * @subpackage model
 * @author     Gustavo Lacoste <gustavo@lacosox.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Local extends BaseLocal
{
    public static $geometryColumn = array('the_geom' => 4326);
    
    public function countActiveLocals()
    {
      $q = Doctrine_Query::create()
        ->from('Local l');

      return Doctrine::getTable('Local')->countActiveLocals($q);
    }
    
}
