# default values
all:
    sf_guard_plugin:
        routes_register: false 
        success_signin_url: homepage
        success_signout_url: homepage 
        #success_signin_url:      @my_route?param=value # el plugin usa la referencia como defecto
        #success_signout_url:     module/action         # el plugin usa la referencia como defecto
    
    # geoSearch config values
    geoSearch:
        searchSiteSuggestEnabled: true
        searchTermSuggestEnabled: true
        
        db_name: fondef_db
        db_host: localhost
        db_user: fondef_usr
        db_pass: fonvs11
        
        googleMapsEnterpriseKey: ''

          
