default:
    http_metas:
        content-type: text/html; charset=utf-8

    metas:
        author:       Gustavo Lacoste (gustavo@lacosox.org)
        title:        Sistema
        description:  Desc
        keywords:     puntoseguro, DAL
        language:     es 
        robots:       all


    stylesheets:
        - 960.min.css
        - master.css


    javascripts:
        - geo_search.js

    has_layout:     true
    layout:         layout
